USE Jardineria_Staging;

-- 1️⃣ Comprobar valores nulos
SELECT COUNT(*) AS NULOS_NOMBRE_CLIENTE
FROM CLIENTES
WHERE NOMBRE_CLIENTE IS NULL OR NOMBRE_CLIENTE = '';

SELECT COUNT(*) AS NULOS_FECHA_PEDIDO
FROM PEDIDOS
WHERE FECHA_PEDIDO IS NULL;

-- 2️⃣ Buscar duplicados en claves de negocio
SELECT ID_CLIENTE, COUNT(*) AS REPETIDOS
FROM CLIENTES
GROUP BY ID_CLIENTE
HAVING COUNT(*) > 1;

SELECT ID_PEDIDO, COUNT(*) AS REPETIDOS
FROM PEDIDOS
GROUP BY ID_PEDIDO
HAVING COUNT(*) > 1;

-- 3️⃣ Validar coherencia de datos importados
SELECT *
FROM PRODUCTOS
WHERE PRECIO_VENTA < 0 OR CANTIDAD_EN_STOCK < 0;

-- 4️⃣ Comparar conteos con la base original (verificar carga completa)
SELECT 
    (SELECT COUNT(*) FROM jardineria) AS ORIGINAL_CLIENTES,
    (SELECT COUNT(*) FROM CLIENTES) AS STAGING_CLIENTES;

SELECT 
    (SELECT COUNT(*) FROM jardineria.PEDIDOS) AS ORIGINAL_PEDIDOS,
    (SELECT COUNT(*) FROM PEDIDOS) AS STAGING_PEDIDOS;

SELECT 
    (SELECT COUNT(*) FROM jardineria.PRODUCTOS) AS ORIGINAL_PRODUCTOS,
    (SELECT COUNT(*) FROM PRODUCTOS) AS STAGING_PRODUCTOS;

-- 5️⃣ Verificar consistencia de claves foráneas
SELECT P.ID_PEDIDO
FROM PEDIDOS P
LEFT JOIN CLIENTES C ON P.ID_CLIENTE = C.ID_CLIENTE
WHERE C.ID_CLIENTE IS NULL;

